version: '2'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: food

  ied-new:
    build: ./
    ports:
      - "8081:8081"
    links:
      - mariadb
